<?php


/*
 * implements hook_enable
 */
function lotto_bets_enable(){
    
}

/*
 * implements hook_disable
 */
function lotto_bets_disable(){
  
}

/**
 * Implements hook_install().
 */
function lotto_bets_install() {
  
    //drupal_install_schema('mt_core');  
   
}

/**
 * Implements hook_uninstall().
 */
function lotto_bets_uninstall() {
    //drupal_uninstall_schema('mt_core');
    
}
?>