<?php
Function get_schema_lotto_keno(&$schema){
$schema['lotto_keno'] = array(
  'description' => 'TODO: please describe this table!',
  'fields' => array(
    'lkid' => array(
      'description' => 'Add description',
      'type' => 'serial',
      'not null' => TRUE,
    ),
    'draw_number' => array(
      'description' => 'Add description',
      'type' => 'int',
      'not null' => TRUE,
    ),
    'draw_date' => array(
      'description' => 'Add description',
      'type' => 'int',
      'not null' => TRUE,
    ),
    'bm' => array(
      'description' => 'Add description',
      'type' => 'int',
      'not null' => TRUE,
    ),
    'n1' => array(
      'description' => 'Add description',
      'type' => 'int',
      'not null' => TRUE,
    ),
    'n2' => array(
      'description' => 'Add description',
      'type' => 'int',
      'not null' => TRUE,
    ),
    'n3' => array(
      'description' => 'Add description',
      'type' => 'int',
      'not null' => TRUE,
    ),
    'n4' => array(
      'description' => 'Add description',
      'type' => 'int',
      'not null' => TRUE,
    ),
    'n5' => array(
      'description' => 'Add description',
      'type' => 'int',
      'not null' => TRUE,
    ),
    'n6' => array(
      'description' => 'Add description',
      'type' => 'int',
      'not null' => TRUE,
    ),
    'n7' => array(
      'description' => 'Add description',
      'type' => 'int',
      'not null' => TRUE,
    ),
    'n8' => array(
      'description' => 'Add description',
      'type' => 'int',
      'not null' => TRUE,
    ),
    'n9' => array(
      'description' => 'Add description',
      'type' => 'int',
      'not null' => TRUE,
    ),
    'n10' => array(
      'description' => 'Add description',
      'type' => 'int',
      'not null' => TRUE,
    ),
    'n11' => array(
      'description' => 'Add description',
      'type' => 'int',
      'not null' => TRUE,
    ),
    'n12' => array(
      'description' => 'Add description',
      'type' => 'int',
      'not null' => TRUE,
    ),
    'n13' => array(
      'description' => 'Add description',
      'type' => 'int',
      'not null' => TRUE,
    ),
    'n14' => array(
      'description' => 'Add description',
      'type' => 'int',
      'not null' => TRUE,
    ),
    'n15' => array(
      'description' => 'Add description',
      'type' => 'int',
      'not null' => TRUE,
    ),
    'n16' => array(
      'description' => 'Add description',
      'type' => 'int',
      'not null' => TRUE,
    ),
    'n17' => array(
      'description' => 'Add description',
      'type' => 'int',
      'not null' => TRUE,
    ),
    'n18' => array(
      'description' => 'Add description',
      'type' => 'int',
      'not null' => TRUE,
    ),
    'n19' => array(
      'description' => 'Add description',
      'type' => 'int',
      'not null' => TRUE,
    ),
    'n20' => array(
      'description' => 'Add description',
      'type' => 'int',
      'not null' => TRUE,
    ),
  ),
  'primary key' => array('lkid'),
);
}
?>